services:
  - type: worker
    name: lotobot-worker
    runtime: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python bot_loto.py
    envVars:
      - key: BOT_TOKEN
        value: 8259151994:AAGcJzQwOZm-GRi14wt8wS-H6T17-JZJKck
